#' Categorises OSM's keys
#'
#' @description
#' Generates a hierarchical categorisation of OSM keys, based on the type of information they convey. 
#' For a given dataframe, this function generates two extra columns called `top_key` and `parent_key` whose values will depend on the values from the this function.
#' 
#' @param df a dataframe with keys and values generated by [extract_and_combine_tags()]
#'
#' @returns a new dataframe with the same columns and two extra ones called `top_key` and `parent_key` with values defined by this function.
#' @export
#'
#' @examples
#' df <- data.frame(
#'  key = c("wheelchair", "building:levels", "highway")
#' )
#' categorise_keys(df)
#' 
categorise_keys <- function(df) {
  accessibility_keys <- c(
    "wheelchair", "ramp", "tactile_paving", "traffic_signals:sound",
    "traffic_signals:vibration", "bench",
    "handrail"
  )
  amenity_keys <- c("cuisine", "opening_hours", "operator", "phone", "website")

  highway_keys <- c(
    "access", "barrier", "bench", "bin", "bridge", "handrail", "highway", "incline", "lanes", "lit", "oneway",
    "ramp", "sac_scale", "segregated", "service", "smoothness", "tracktype", "width"
  )
  motor_keys <- c("motor", "maxspeed", "traffic_calming", "vehicle", "direction", "lanes", "lane_markings")

  transport_keys <- c("electrified", "gauge", "railway", "tunnel", "shoulder")

  nature_keys <- c("crop", "water", "intermittent")

  leisure_keys <- c("sauna", "swimming_pool")

  qa_keys <- c("ref")

  edi_keys <- c("lgbtq", "women")

  power_keys <- (c("frequency", "generator", "power", "voltage"))

  references_keys <- c("wikidata", "wikipedia")

  boundaries_keys <- c("admin_level", "boundary", "landuse")

  df <- df |>
    dplyr::mutate(
      parent_key = dplyr::case_when(
        key %in% accessibility_keys ~ "accessibility",
        stringr::str_detect(key, "wheelchair") ~ "accessibility",
        stringr::str_detect(key, "emergency|health|hospital|medical|shelter|social_facility") ~ "care",
        stringr::str_detect(key, "contact|email|opening_hours|phone|website") ~ "contact",
        stringr::str_detect(key, "cycle|cyclability") ~ "cycling",
        stringr::str_detect(key, "heritage") ~ "heritage",
        key %in% motor_keys ~ "motor",
        stringr::str_detect(key, "maxspeed|vehicle|direction|lanes|parking") ~ "motor",
        stringr::str_detect(key, "foot|sidewalk|kerb") ~ "pedestrian",
        stringr::str_detect(key, "tourism") ~ "tourism"
      ),
      top_key = dplyr::case_when(
        stringr::str_detect(key, "addr") ~ "Addresses",
        key %in% amenity_keys ~ "Amenities",
        stringr::str_detect(key, "amenity|brand|diet|operator|shop") ~ "Amenities",
        parent_key %in% c("care", "contact", "tourism", "heritage") ~ "Amenities",
        stringr::str_detect(key, "roof|building|architect") ~ "Buildings",
        stringr::str_detect(key, "crossing|traffic_signals") ~ "Crossings",
        key %in% edi_keys ~ "EDI",
        stringr::str_detect(key, "name") & !stringr::str_detect(key, "housename") ~ "Names",
        key %in% nature_keys ~ "Nature Resources",
        stringr::str_starts(key, "natural|nature|water|river|tree|grass") ~ "Nature Resources",
        key %in% leisure_keys ~ "Leisure",
        stringr::str_detect(key, "leisure|sport") & !stringr::str_detect(key, "transport") ~ "Leisure",
        stringr::str_detect(key, "bus|naptan|public_transport|button_operated") ~ "Public transport",
        key %in% qa_keys ~ "Quality Assurance",
        stringr::str_starts(key, "check_date|source|survey") ~ "Quality Assurance",
        key %in% highway_keys ~ "Streets",
        stringr::str_detect(parent_key, "cycling|pedestrian") ~ "Streets",
        stringr::str_detect(key, "surface|tactile_paving") ~ "Streets",
        key %in% transport_keys ~ "Transport",
        stringr::str_detect(key, "motor") ~ "Transport",
        stringr::str_detect(key, references_keys) ~ "External references",
        key %in% power_keys ~ "Power",
        stringr::str_detect(key, paste(power_keys, collapse = "|")) ~ "Power"
      )
    )

  return(df)
}
