#' Retrieves changesets by a set of user(s)
#'
#' Parses a list of usernames and queries OSM api using
#' [osmapiR::osm_query_changesets()] to retrieve all the individual changesets
#' and then combines the results in a single dataframe.
#'
#' @param users a character vector containing OSM usernames.
#' @param n_changesets a number specifying the maximum number of changesets to
#'   be retrieved per user, starting from the most recent ones.
#'
#' @returns a dataframe containing all changesets' details authored by the
#'   selected users.
#' @export
#'
get_contributions_changesets <- function(
    users,
    n_changesets = 100) {
  changesets <- data.frame()

  for (user in users) {
    print(user)

    tmp_changesets <- osmapiR::osm_query_changesets(
      user = user,
      format = "sf",
      tags_in_columns = TRUE,
      limit = n_changesets
    )

    if (nrow(changesets) == 0) {
      changesets <- as.data.frame(tmp_changesets)
    } else {
      changesets <- dplyr::full_join(
        changesets, as.data.frame(tmp_changesets),
        by = intersect(names(changesets), names(tmp_changesets))
      )
    }

    rm(tmp_changesets)
  }

  return(changesets)
}

#' Retrieve Changesets' details.
#'
#' Retrieves all the details from a list of changesets ids by querying
#' [osmapiR::osm_download_changeset()] for each changeset and then combining all
#' the results in a single dataframe.
#'
#' @param changeset_ids a vector containing changesets ids to be queried.
#'
#' @returns a dataframe describing all changes associated with the changesets.
#' @export
#'
get_changesets_details <- function(changeset_ids) {

  changesets_details <- data.frame()
  tags_used <- data.frame()

  for (changeset in changeset_ids) {
    tmp.changesets_details <- osmapiR::osm_download_changeset(changeset)

    changesets_details <- changesets_details |>
      dplyr::bind_rows(tmp.changesets_details)

    # TODO: some changesets are split in more than one part: modify, delete... the
    # lines below fail when there's more than one row with a changeset id.

    # tmp.tags <-  as.data.frame(tmp.changesets_details$tags) |>
    #   mutate(changeset = changeset)
    #


    # tags_used <- tags_used |>
    # bind_rows(tmp.tags)

  }

  return(changesets_details)

}

#' Extract nested keys and values from changesets
#'
#' [get_contributions_changesets()] returns a dataframe with a column `tags`
#' that contains nested dataframes. This function extracts the embedded
#' dataframes while preserving the original changeset id.
#'
#'
#' @param df a dataframe generated by
#'   [get_contributions_changesets()]. It expects
#'
#' @returns a dataframe containing all keys and values used in every changeset.
#' @export
#'
extract_and_combine_tags <- function(df) {

  # Check if the 'tags' column exists
  if (!"tags" %in% names(changesets_details)) {
    stop("The 'tags' column is not present in the changesets_details dataframe.")
  }

  combined_tags <- df |>
    dplyr::rowwise() |>
    dplyr::mutate(tags_df = list(as.data.frame(tags))) |> # Convert each nested tags to a dataframe
    tidyr::unnest(tags_df) |> # Unnest the tags dataframes
    dplyr::select(-tags, -members) # Include the id column with the tags

  return(combined_tags)
}
